package ai.alagent.core.database

import androidx.room.*

@Entity(tableName="sessions", indices=[Index("created_at")]) data class SessionEntity(@PrimaryKey val id:String,@ColumnInfo(name="created_at") val createdAt:Long,@ColumnInfo(name="updated_at") val updatedAt:Long,@ColumnInfo(name="privacy_mode",defaultValue="0") val privacyMode:Boolean=false)
@Entity(tableName="tasks", foreignKeys=[ForeignKey(entity=SessionEntity::class,parentColumns=["id"],childColumns=["session_id"],onDelete=ForeignKey.CASCADE)],indices=[Index("session_id"),Index("status")]) data class TaskEntity(@PrimaryKey val id:String,@ColumnInfo(name="session_id") val sessionId:String,val goal:String,val status:String,@ColumnInfo(name="created_at") val createdAt:Long)
@Entity(tableName="turns", foreignKeys=[ForeignKey(entity=SessionEntity::class,parentColumns=["id"],childColumns=["session_id"],onDelete=ForeignKey.CASCADE),ForeignKey(entity=TaskEntity::class,parentColumns=["id"],childColumns=["task_id"],onDelete=ForeignKey.CASCADE)],indices=[Index("session_id"),Index("task_id"),Index("timestamp")]) data class TurnEntity(
    @PrimaryKey val id:String,
    @ColumnInfo(name="session_id") val sessionId:String,
    @ColumnInfo(name="task_id") val taskId:String,
    val timestamp:Long,
    val model:String,
    val provider:String,
    @ColumnInfo(name="prompt_version") val promptVersion:String,
    @ColumnInfo(name="tool_definitions_json",defaultValue="[]") val toolDefinitionsJson:String="[]",
    @ColumnInfo(name="input_tokens") val inputTokens:Int?,
    @ColumnInfo(name="output_tokens") val outputTokens:Int?,
    @ColumnInfo(name="latency_ms") val latencyMs:Long?,
    @ColumnInfo(name="verification_status") val verificationStatus:String?=null,
    @ColumnInfo(name="retry_count") val retryCount:Int,
    @ColumnInfo(name="errors_json",defaultValue="[]") val errorsJson:String="[]",
    @ColumnInfo(name="stop_reason") val stopReason:String?
)
@Entity(tableName="messages", foreignKeys=[ForeignKey(entity=SessionEntity::class,parentColumns=["id"],childColumns=["session_id"],onDelete=ForeignKey.CASCADE)],indices=[Index("session_id"),Index("created_at")]) data class MessageEntity(@PrimaryKey val id:String,@ColumnInfo(name="session_id") val sessionId:String,val role:String,val content:String,@ColumnInfo(name="created_at") val createdAt:Long)
@Entity(tableName="tool_calls", foreignKeys=[ForeignKey(entity=TurnEntity::class,parentColumns=["id"],childColumns=["turn_id"],onDelete=ForeignKey.CASCADE)],indices=[Index("turn_id"),Index("tool_id")]) data class ToolCallEntity(@PrimaryKey val id:String,@ColumnInfo(name="turn_id") val turnId:String,@ColumnInfo(name="tool_id") val toolId:String,@ColumnInfo(name="arguments_json") val argumentsJson:String,@ColumnInfo(name="result_json") val resultJson:String?,val status:String,@ColumnInfo(name="duration_ms") val durationMs:Long?)
@Entity(tableName="observations", foreignKeys=[ForeignKey(entity=TurnEntity::class,parentColumns=["id"],childColumns=["turn_id"],onDelete=ForeignKey.CASCADE)],indices=[Index("turn_id")]) data class ObservationEntity(@PrimaryKey val id:String,@ColumnInfo(name="turn_id") val turnId:String,val kind:String,val summary:String,@ColumnInfo(name="payload_json") val payloadJson:String?,val signature:String?,@ColumnInfo(name="created_at") val createdAt:Long)
@Entity(tableName="verification_results", foreignKeys=[ForeignKey(entity=ToolCallEntity::class,parentColumns=["id"],childColumns=["tool_call_id"],onDelete=ForeignKey.CASCADE)],indices=[Index("tool_call_id")]) data class VerificationResultEntity(@PrimaryKey val id:String,@ColumnInfo(name="tool_call_id") val toolCallId:String,val status:String,@ColumnInfo(name="evidence_json") val evidenceJson:String,val reason:String?,@ColumnInfo(name="created_at") val createdAt:Long)
@Entity(tableName="memories",indices=[Index("kind"),Index("updated_at")]) data class MemoryEntity(@PrimaryKey val id:String,val kind:String,val text:String,val confidence:Double,@ColumnInfo(name="updated_at") val updatedAt:Long)
@Entity(tableName="memory_embeddings", foreignKeys=[ForeignKey(entity=MemoryEntity::class,parentColumns=["id"],childColumns=["memory_id"],onDelete=ForeignKey.CASCADE)],indices=[Index("memory_id",unique=true)]) data class MemoryEmbeddingEntity(@PrimaryKey val id:String,@ColumnInfo(name="memory_id") val memoryId:String,val dimensions:Int,val vector:ByteArray,@ColumnInfo(name="model_id") val modelId:String)
@Entity(tableName="todos", foreignKeys=[ForeignKey(entity=TaskEntity::class,parentColumns=["id"],childColumns=["task_id"],onDelete=ForeignKey.CASCADE)],indices=[Index("task_id")]) data class TodoEntity(@PrimaryKey val id:String,@ColumnInfo(name="task_id") val taskId:String,val text:String,val status:String,val position:Int)
@Entity(tableName="scratchpad_entries", foreignKeys=[ForeignKey(entity=TaskEntity::class,parentColumns=["id"],childColumns=["task_id"],onDelete=ForeignKey.CASCADE)],indices=[Index("task_id")]) data class ScratchpadEntryEntity(@PrimaryKey val id:String,@ColumnInfo(name="task_id") val taskId:String,val text:String,@ColumnInfo(name="created_at") val createdAt:Long)
@Entity(tableName="skills",indices=[Index("skill_id",unique=true)]) data class SkillEntity(@PrimaryKey val id:String,@ColumnInfo(name="skill_id") val skillId:String,val version:String,val name:String,val description:String,val enabled:Boolean,@ColumnInfo(name="manifest_json") val manifestJson:String)
@Entity(tableName="skill_runs", foreignKeys=[ForeignKey(entity=SkillEntity::class,parentColumns=["id"],childColumns=["skill_row_id"],onDelete=ForeignKey.CASCADE)],indices=[Index("skill_row_id"),Index("started_at")]) data class SkillRunEntity(@PrimaryKey val id:String,@ColumnInfo(name="skill_row_id") val skillRowId:String,@ColumnInfo(name="started_at") val startedAt:Long,@ColumnInfo(name="ended_at") val endedAt:Long?,val status:String)
@Entity(tableName="models",indices=[Index("provider_id")]) data class ModelEntity(@PrimaryKey val id:String,@ColumnInfo(name="provider_id") val providerId:String?,@ColumnInfo(name="display_name") val displayName:String,val family:String,val format:String,val quantization:String?,@ColumnInfo(name="size_bytes") val sizeBytes:Long?,@ColumnInfo(name="context_window") val contextWindow:Int,@ColumnInfo(name="capabilities_json") val capabilitiesJson:String,@ColumnInfo(name="metadata_json") val metadataJson:String)
@Entity(tableName="model_downloads", foreignKeys=[ForeignKey(entity=ModelEntity::class,parentColumns=["id"],childColumns=["model_id"],onDelete=ForeignKey.CASCADE)],indices=[Index("model_id",unique=true),Index("status")]) data class ModelDownloadEntity(@PrimaryKey val id:String,@ColumnInfo(name="model_id") val modelId:String,val url:String,@ColumnInfo(name="destination_path") val destinationPath:String,@ColumnInfo(name="bytes_downloaded") val bytesDownloaded:Long,@ColumnInfo(name="total_bytes") val totalBytes:Long?,val checksum:String?,val status:String,@ColumnInfo(name="updated_at") val updatedAt:Long)
@Entity(tableName="providers") data class ProviderEntity(@PrimaryKey val id:String,val type:String,@ColumnInfo(name="display_name") val displayName:String,val enabled:Boolean)
@Entity(tableName="provider_configs", foreignKeys=[ForeignKey(entity=ProviderEntity::class,parentColumns=["id"],childColumns=["provider_id"],onDelete=ForeignKey.CASCADE)],indices=[Index("provider_id",unique=true)]) data class ProviderConfigEntity(@PrimaryKey val id:String,@ColumnInfo(name="provider_id") val providerId:String,@ColumnInfo(name="base_url") val baseUrl:String?,@ColumnInfo(name="secret_alias") val secretAlias:String?,@ColumnInfo(name="config_json") val configJson:String)
@Entity(tableName="schedules",indices=[Index("next_run"),Index("status")]) data class ScheduleEntity(@PrimaryKey val id:String,val name:String,val schedule:String,val goal:String,@ColumnInfo(name="allowed_tools_json") val allowedToolsJson:String,@ColumnInfo(name="model_id") val modelId:String?,@ColumnInfo(name="permission_policy_json") val permissionPolicyJson:String,@ColumnInfo(name="last_run") val lastRun:Long?,@ColumnInfo(name="next_run") val nextRun:Long?,val status:String)
@Entity(tableName="audit_events",indices=[Index("timestamp"),Index("session_id"),Index("task_id")]) data class AuditEventEntity(@PrimaryKey val id:String,val timestamp:Long,@ColumnInfo(name="session_id") val sessionId:String?,@ColumnInfo(name="task_id") val taskId:String?,@ColumnInfo(name="turn_id") val turnId:String?,val component:String,val level:String,@ColumnInfo(name="event_type") val eventType:String,@ColumnInfo(name="metadata_json") val metadataJson:String)
@Entity(tableName="attachments", foreignKeys=[ForeignKey(entity=MessageEntity::class,parentColumns=["id"],childColumns=["message_id"],onDelete=ForeignKey.CASCADE)],indices=[Index("message_id")]) data class AttachmentEntity(@PrimaryKey val id:String,@ColumnInfo(name="message_id") val messageId:String,val uri:String,@ColumnInfo(name="mime_type") val mimeType:String,@ColumnInfo(name="display_name") val displayName:String?,@ColumnInfo(name="size_bytes") val sizeBytes:Long?)
@Entity(tableName="prompt_versions",indices=[Index("prompt_id"),Index(value=["prompt_id","version"],unique=true)]) data class PromptVersionEntity(@PrimaryKey val id:String,@ColumnInfo(name="prompt_id") val promptId:String,val version:Int,val content:String,val checksum:String,@ColumnInfo(name="created_at") val createdAt:Long)
@Entity(tableName="evaluation_runs",indices=[Index("started_at"),Index("suite_id")]) data class EvaluationRunEntity(@PrimaryKey val id:String,@ColumnInfo(name="suite_id") val suiteId:String,@ColumnInfo(name="started_at") val startedAt:Long,@ColumnInfo(name="ended_at") val endedAt:Long?,@ColumnInfo(name="metrics_json") val metricsJson:String,val status:String)
